---

- name: Create user
  user:
    name: "{{ nginx_static_id }}"
    group: "{{ nginx_static_group }}"
    comment: "Static Website - {{ nginx_static_id }}"
    home: "{{ nginx_static_base_path }}/{{ nginx_static_id }}"
    createhome: no
    shell: /sbin/nologin
    password: "!!"
    update_password: always
    state: present
  when: (nginx_static_type != 'redirect') or (not is_docker) or (not is_vagrant)

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ nginx_static_id }}"
    group: "{{ nginx_static_group }}"
  with_items:
    - "{{ nginx_static_base_path }}/{{ nginx_static_id }}"
  when: (nginx_static_type != 'redirect') or (not is_docker) or (not is_vagrant)
  notify:
    - genhomedircon
    - restorecon /srv/www

- name: Update authorized_keys
  authorized_key:
    user: "{{ nginx_static_id }}"
    key: "{{ nginx_static_authorized_key }}"
    exclusive: yes
    manage_dir: yes
    state: present
  when: (nginx_static_type != 'redirect') or (not is_docker) or (not is_vagrant)

- name: Configure nginx
  template:
    src: "{{ nginx_static_type }}.conf.j2"
    dest: "/etc/nginx/conf.d/{{ nginx_static_id }}.conf"
    owner: root
    group: root
    mode: '0644'
    backup: no
  notify:
    - restart nginx
  tags:
    - configure
